backend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'image_groups/index'
    get 'image_groups/show'
    get 'configuracion_sitio', to: 'configuracion_sitio#index'
    resources :users
    resources :products
    resources :categories
    resources :tags
    resource :logos, only: [:edit, :update, :destroy, :show]
    resources :image_groups
    resources :products do
      member do
        delete 'remove_image/:image_id', to: 'products#remove_image', as: 'remove_image'
        delete 'remove_main_image/:main_image_id', to: 'products#remove_main_image', as: 'remove_main_image'
      end
    end
    resources :image_groups do
      member do
        get 'view', to: 'image_groups#view'
        post 'select', to: 'image_groups#select'
        patch :update, to: 'image_groups#update'
        delete :remove_image, to: 'image_groups#remove_image'
      end
      get 'favorite_image_group', on: :collection, to: 'image_groups#show_favorite', defaults: { format: :json }
    end
  end
  get 'tags', to: 'public_routes#show_tags', defaults: { format: :json }
  get 'categories', to: 'public_routes#show_categories', defaults: { format: :json }
  get 'logo', to: 'public_routes#show_logo', defaults: { format: :json }
  get 'favorite', to: 'public_routes#show_favorite', defaults: { format: :json }
  get 'products', to: 'public_routes#products', defaults: { format: :json }
  get 'products/:id', to: 'public_routes#show_product', defaults: { format: :json }
  get 'random_products', to: 'public_routes#random_products', defaults: { format: :json }
  get 'total_pages', to: 'public_routes#total_pages', defaults: { format: :json }
  get 'pages/home'
  root to: 'pages#home' 
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

end

backend/app/models/product.rb
class Product < ApplicationRecord
   # Validaciones
   validates :name, presence: true, uniqueness: true, if: :name_changed?, length: { minimum: 2, maximum: 255 }
   validates :description, presence: true
   validate :at_least_one_tag_selected
   validate :main_image_presence_on_create, on: :create
   validate :category_must_be_present

   # Atributos por defecto
   attribute :price, default: 0.0
   attribute :cost, default: 0.0
   attribute :active, default: true
 
  # Asociaciones
  belongs_to :category
  has_and_belongs_to_many :tags
  has_many_attached :images
  has_one_attached :main_image

  # generate internal code
  before_create :generate_unique_code

  HUMANIZED_ATTRIBUTES = {
    :name => "Nombre", 
    :description => "Descripcion",
    :images => "",
    :tags => "",
    :category => "",
    :main_image => "",
}


def category_must_be_present
  if category_id.blank?
    errors.add(:category, "Selecciona una categoria.")
  end
end

def self.human_attribute_name(attr, options={})
  HUMANIZED_ATTRIBUTES[attr.to_sym] || super
end
  

def self.filtered_and_sorted(params)
  begin
    retries = 10  # Número de intentos permitidos en caso de error de la base de datos
    includes(:images).all
    products = includes(:tags).paginate(page: params[:page], per_page: 12)

    if params[:sort_by_price].present?
      products = products.sort_by_price(params[:sort_by_price])
    end

    if params[:category_id].present?
      products = products.filter_by_category(params[:category_id])
    end

    if params.dig(:product, :tag_ids).is_a?(Array)
      tag_ids = params.dig(:product, :tag_ids).reject(&:empty?)
      products = products.filter_by_tags(tag_ids) if tag_ids.any?
    end

    if params[:name].present?
      products = products.filter_by_name(params[:name])
    end

    if params[:sort_by_creation] == "newest_first"
      products = products.sort_by_creation("newest_first")
    elsif params[:sort_by_creation] == "oldest_first"
      products = products.sort_by_creation("oldest_first")
    end

    if params[:sort_order] == "asc"
      products = products.sort_by_name("asc")
    elsif params[:sort_order] == "desc"
      products = products.sort_by_name("desc")
    end

    return products
  rescue ActiveRecord::StatementInvalid => e
    Rails.logger.error("Error en la consulta de la base de datos: #{e.message}")
    Rails.logger.error(e.backtrace.join("\n"))
    if retries > 0
      retries -= 1
      sleep(1) # Agregar una pausa antes de intentar nuevamente
      retry
    else
      raise e  # Vuelve a lanzar la excepción en caso de agotar los intentos
    end
  end
end


# scope
scope :sort_by_price, ->(order) { order(price: (order == 'desc' ? :desc : :asc)) if order.present? }
scope :filter_by_category, ->(category_id) { where(category_id: category_id) if category_id.present? }
scope :filter_by_tags, ->(tag_ids) { joins(:tags).where(tags: { id: tag_ids }).distinct if tag_ids.is_a?(Array) && tag_ids.any? }
scope :filter_by_name, ->(name) { where("name LIKE ?", "%#{name}%") if name.present? }
scope :sort_by_creation, ->(order) { order(created_at: (order == "newest_first" ? :desc : :asc)) if order.present? }
scope :sort_by_name, ->(order) { order(name: (order == "asc" ? :asc : :desc)) if order.present? }

  private

  def generate_unique_code
    loop do
      self.internal_code = SecureRandom.hex(4).upcase
      break unless Product.exists?(internal_code: self.internal_code)
    end
  end
 
  def at_least_one_tag_selected
    if tag_ids.blank?
      errors.add(:base, "Almenos un tag debe ser seleccionado.")
    end
  end  
  def main_image_presence_on_create
    if  !main_image.attached?
      errors.add(:main_image, "Debe haber almenos una imagen principal")
    end
  end
end

backend/app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    def index
      @products = Product.filtered_and_sorted(params)
    end
  
    def show
      @product = Product.find(params[:id])
    end
  
    def new
      @product = Product.new
    end
  
    def edit
    end
  
    def create
      @product = Product.new(product_params)
  
      @product.tags = Tag.where(id: params[:product][:tag_ids])
  
      if @product.save
        redirect_to admin_products_path, notice: "El producto fue creado con exito."
      else
        render :new, alert: "El producto no pudo ser creado."
      end
    end
  
    def update
      @product.category = Category.find(params[:product][:category_id])
      @product.tags = Tag.where(id: params[:product][:tag_ids])
  
      if @product.update(product_params)
        redirect_to admin_products_path, notice: "El producto fue actualizado con exito."
      else
        render :edit, alert: "El producto no pudo ser actualizado."
      end
    end
  

    def remove_image
      @product = Product.find(params[:id])
      image = @product.images.find(params[:image_id])
    
      if image.purge
        redirect_to edit_admin_product_path(@product), notice: 'Imagen removida con éxito.'
      else
        redirect_to edit_admin_product_path(@product), alert: 'Error al remover la imagen.'
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to edit_admin_product_path(@product), alert: 'La imagen no pudo ser encontrada.'
    end

def remove_main_image
  @product = Product.find(params[:id])

  if @product.main_image.attached?
    if @product.main_image.purge
      redirect_to edit_admin_product_path(@product), notice: 'Imagen removida con éxito.'
    else
      redirect_to edit_admin_product_path(@product), notice: 'Imagen removida con éxito.'
    end
  else
    redirect_to edit_admin_product_path(@product), alert: 'La imagen no pudo ser encontrada.'
  end
rescue ActiveRecord::RecordNotFound
  redirect_to edit_admin_product_path(@product), alert: 'Product not found.'
end

    
  
    def destroy
      if @product.destroy
        redirect_to admin_products_url, notice: 'Producto removido con éxito.'
      else
        redirect_to admin_products_url, alert: 'Error al remover el producto.'
      end
    end
    
    private
  
    def set_product
      @product = Product.find(params[:id])
    end
  
    def product_params
      params.require(:product).permit(:name, :description, :internal_code,:main_image, :price, :cost, :active, :category_id, :sort_by_price, tag_ids: [], images: [])
    end
  end
  

backend/app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], local: true, class:"row g-3") do |form| %>
  <% if product.errors.any? %>
    <div id="product-flash-messages" class="products-alerts">
        <% product.errors.full_messages.each do |message| %>
          <div class="product-alert"><%= message %></div>
        <% end %>
    </div>
  <% end %>
  <div class="form-group col-md-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="form-group col-md-4">
    <%= form.label :descripcion %>
    <%= form.text_area :description, class: "form-control", required: true  %>
  </div>
   <div class="form-group col-md-4">
    <%= form.label :categoria %>
    <%= form.collection_select(:category_id, Category.all, :id, :name, { prompt: 'Select a Category' }, class: "form-control", required: true ) %>
  </div>
  <div class="form-group col-md-4">
    <%= form.label :costo %>
    <%= form.text_field :cost, class: "form-control", required: true  %>
  </div>
    <div class="form-group col-md-4">
    <%= form.label :precio %>
    <%= form.text_field :price, class: "form-control" , required: true %>
  </div>

<div class="col-md-4">
   <%= form.label :activo, class: "form-check-label" %>
    <%= form.check_box :active, class: "form-check-input"%>
</div>
<div class="col-md-4">
 <%= form.label :imagen_principal %>
<%= form.file_field :main_image, class: "form-control" %>
 <% if product.main_image.attached? && action_name == "edit" %>
      <p>Imagen actual:</p>
      <ul class="thumbnail-product">
          <% if product.persisted? && product.main_image.id.present? %>
            <li >
              <%= image_tag product.main_image, class: 'img-thumbnail',style: 'max-width: 70px; max-height: 70px;', loading: 'lazy' %>
              <%= link_to 'Borrar', remove_main_image_admin_product_path(product, main_image_id: product.main_image.id), method: :delete, data: { confirm: 'Estás seguro?' }, class:"btn btn-danger" %>
            </li>
        <% end %>
      </ul>
    <% end %>
</div>
  <div class="form-group col-md-4">
    <%= form.label :imagenes_adicionales %>
    <%= form.file_field :images, multiple: true, class: "form-control" %>

    <% if product.images.attached? && action_name == "edit" %>
      <p>Imagenes actuales:</p>
      <ul class="thumbnail-product">
        <% product.images.each do |image| %>
          <% if product.persisted? && image.id.present? %>
            <li>
              <%= image_tag image, class: 'img-thumbnail',style: 'max-width: 70px; max-height: 70px;', loading: 'lazy' %>
              <%= link_to 'Borrar', remove_image_admin_product_path(product, image_id: image.id), method: :delete, data: { confirm: 'Estás seguro?' }, class:"btn btn-danger" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="form group col-md-4">
<p>Tags<p>
<% Tag.all.each do |tag| %>
  <div class="form-check">
      <%= collection_check_boxes(:product, :tag_ids, [tag], :id, :tagname, { checked: params.dig(:product, :tag_ids) }, multiple: true, class: 'form-check-input' ) %>
  </div>
<% end %>
</div>
  <div class="form-group col-md-4">
  </div>
  <div class="form-group">
    <% if action_name == "edit" %>
    <div class="btn-group">
      <%= form.submit "Actualizar", class: "btn btn-primary" %>
      <%= link_to 'Atras', admin_products_path, class:"btn btn-secondary" %>
      </div>
    <% else %>
    <div class="btn-group">
      <%= form.submit "Crear", class: "btn btn-primary" %>
      <%= link_to 'Atras', admin_products_path, class:"btn btn-secondary" %>
      </div>
    <% end %>
  </div>
<% end %>

backend/app/views/admin/products/edit.html.erb
<h1>Editando el producto</h1>

<%= render 'form', product: @product %>

backend/app/views/admin/products/index.html.erb
<h1>Productos</h1>

<div class="table-responsive">
<table class="table table-sm table-dark table-striped table-hover">
<thead>
<tr>
<th>Nombre</th>
<th>Descripcion</th>
<th>Codigo interno</th>
<th>precio</th>
<th>Costo</th>
<th>Activo</th>
<th>Categoria</th>
<th>Imagen</th>
<th>tags</th>
<th>Acciones</th>
</tr>
</thead>

<tbody>

<% @products.each do |product| %>
<tr>
<td><%= product.name %></td>
<td><%= product.description %></td>
<td><%= product.internal_code %></td>
<td><%= product.price %></td>
<td><%= product.cost %></td>
<td><%= product.active %></td>
<td><%= product.category.name %></td>
<td class="img-td">
<% if product.main_image.attached? %>
<%= image_tag product.main_image %>
<% else %>
<p>Este producto no tiene imagen</p>
<% end %>
</td>

<td>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
Ver tags
</a>
<ul class="dropdown-menu dropdown-menu-dark">
<% product.tags.each do |tag| %>
<li class="dropdown-item"><%= tag.tagname %></li>
<li><hr class="dropdown-divider"></li>
<% end %>
</ul>
</li>
</td>

<td >
<div class="btn-group">
<%= link_to 'Ver', admin_product_path(product), class:"btn btn-info" %>
<%= link_to 'Editar', edit_admin_product_path(product), class:"btn btn-primary" %>
<%= link_to 'Borrar', admin_product_path(product), method: :delete, data: { confirm: 'Estas seguro?' }, class:"btn btn-danger" %>
</div>
</td>
</tr>
<% end %>

</tbody>
</table>
<div class="pagination">
<%= will_paginate @products,  previous_label: '<', next_label: '>', page_links: false %>
</div>
</div>
<br>






<div>

<%= form_tag(admin_products_path, method: :get) do %>

<div class="form-group products-list">

<div class="filter-gap"> 
<div>
<%= text_field_tag(:name, params[:name], placeholder: 'Nombre', class:"form-control") %>
</div>

<div>
<%= select_tag(:category_id, options_for_select(Category.all.map { |c| [c.name, c.id] }, params[:category_id]), prompt: 'Categoria', class: "form-control", id: "exampleFormControlSelect1") %>
</div>

<div>
<%= select_tag :sort_order, options_for_select([["Orden alfabetico", ""], ["A to Z", "asc"], ["Z to A", "desc"]], params[:sort_order]), class: "form-control", id: "exampleFormControlSelect1" %>
</div>

<div>
<%= select_tag :sort_by_creation, options_for_select([["Ordenar por fecha", ""], ["Mas nuevo", "newest_first"], ["Mas viejo", "oldest_first"]], params[:sort_by_creation]), class: "form-control", id: "exampleFormControlSelect1" %>
</div>

<div>
<%= select_tag :sort_by_price, options_for_select([["Ordenar por precio", ""], ["Menor a mayor precio", "asc"], ["Mayor a menor precio", "desc"]], params[:sort_by_price]), class: "form-control", id: "exampleFormControlSelect1" %>
</div>

<div class="btn-group" >
<%= submit_tag('Filtrar', class: 'btn btn-primary') %>
<%= link_to 'Nuevo producto', new_admin_product_path, class:"btn btn-success" %>
</div>
</div>


<div>
<p>Tags</p>
<% Tag.all.each do |tag| %>
<div class="form-check">
<%= collection_check_boxes(:product, :tag_ids, [tag], :id, :tagname, { checked: params.dig(:product, :tag_ids) }, multiple: true, class: 'form-check-input') %>
</div>
<% end %>
</div>

</div>
<% end %>
</div>

backend/app/views/admin/products/new.html.erb
<h1>Nuevo producto</h1>

<%= render 'form', product: @product %>

backend/app/views/admin/products/show.html.erb
<h1>Info del prodcuto</h1>

<p>
  <strong>Nombre:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Codigo interno:</strong>
  <%= @product.internal_code %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.price %>
</p>


<p>
  <strong>Costo:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @product.category.name  %>
</p>
<div>
<% @product.tags.each do |tag| %>
<strong>Tags:</strong>
<p ><%= tag.tagname %></p>
<% end %>

<strong>Imagen principal</strong>
<div class="img-td">
<% if @product.main_image.attached? %>
<%= image_tag @product.main_image %>
<% else %>
<p>Este producto no tiene imagen</p>
<% end %>
</div>
</div>
    <% if @product.images.attached?  %>
      <strong>Imagenes actuales:</strong>
      <ul class="thumbnail-product">
        <% @product.images.each do |image| %>
          <% if @product.persisted? && image.id.present? %>
            <li>
              <%= image_tag image, class: 'img-thumbnail',style: 'max-width: 70px; max-height: 70px;', loading: 'lazy' %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>

<div class="btn-group">
<%= link_to 'Editar', edit_admin_product_path(@product), class:"btn btn-primary" %> 
<%= link_to 'Atras', admin_products_path, class:"btn btn-secondary" %>
</div>