backend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'image_groups/index'
    get 'image_groups/show'
    get 'configuracion_sitio', to: 'configuracion_sitio#index'
    resources :users
    resources :products
    resources :categories
    resources :tags
    resource :logos, only: [:edit, :update, :destroy, :show]
    resources :image_groups
    resources :products do
      member do
        delete 'remove_image/:image_id', to: 'products#remove_image', as: 'remove_image'
        delete 'remove_main_image/:main_image_id', to: 'products#remove_main_image', as: 'remove_main_image'
      end
    end
    resources :image_groups do
      member do
        get 'view', to: 'image_groups#view'
        post 'select', to: 'image_groups#select'
        patch :update, to: 'image_groups#update'
        delete :remove_image, to: 'image_groups#remove_image'
      end
      get 'favorite_image_group', on: :collection, to: 'image_groups#show_favorite', defaults: { format: :json }
    end
  end
  get 'tags', to: 'public_routes#show_tags', defaults: { format: :json }
  get 'categories', to: 'public_routes#show_categories', defaults: { format: :json }
  get 'logo', to: 'public_routes#show_logo', defaults: { format: :json }
  get 'favorite', to: 'public_routes#show_favorite', defaults: { format: :json }
  get 'products', to: 'public_routes#products', defaults: { format: :json }
  get 'products/:id', to: 'public_routes#show_product', defaults: { format: :json }
  get 'random_products', to: 'public_routes#random_products', defaults: { format: :json }
  get 'total_pages', to: 'public_routes#total_pages', defaults: { format: :json }
  get 'pages/home'
  root to: 'pages#home' 
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

end

backend/app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    before_destroy :ensure_not_referenced_by_products
    validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 255 }

    self.per_page = 4 

    private
  
    def ensure_not_referenced_by_products
      unless products.empty?
        errors.add(:base, "No puedes eliminar una categoría asociada a productos")
        throw :abort
      end
    end
  end

backend/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        flash[:notice] = 'La categoria fue creada.'
        format.html { redirect_to admin_categories_url }
        format.json { render :index, status: :created, location: @category }
      else
        flash[:alert] = 'No se pudo crear la categoria.'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: 'La categoria fue actualizada.' }
        format.json { render :index, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity, alert: 'No se pudo actualizadar.' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: 'Categoría removida.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_categories_url, alert: 'Error al remover la categoría.' }
        format.json { head :unprocessable_entity }
      end
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'Categoria no encontrada.'
    redirect_to admin_categories_url
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

backend/app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category], local: true) do |form| %>

<div class="form-group form-gutter-categories">
<%= form.label :nombre %>
<%= form.text_field :name, class: "form-control", required: true %>
</div>

<div>
<% if action_name == "edit" %>
<div class="actions btn-group">
<%= form.submit "Actualizar", class:"btn btn-primary" %>
<%= link_to 'Atras', admin_categories_path, class:"btn btn-secondary" %>
</div>
<% else %>
<div class="actions btn-group">
<%= form.submit "Crear" , class:"btn btn-primary"%>
<%= link_to 'Atras', admin_categories_path, class:"btn btn-secondary" %>
</div>
<% end %>
</div>
<% end %>

backend/app/views/admin/categories/edit.html.erb
<h1>Editando Categoria</h1>

<%= render 'form', category: @category %>

backend/app/views/admin/categories/index.html.erb
<h1>Categorias</h1>

<table class="table table-dark table-sm table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Id</th>
      <th>Acciones</th>
    </tr>
  </thead>
<div class="pagination">
<%= will_paginate @categories,  previous_label: '<', next_label: '>', page_links: false %>
</div>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.id %></td>
        <td>
         <div class="btn-group">
        <%= link_to 'Editar', edit_admin_category_path(category), class:"btn btn-primary" %>
        <%= link_to 'Borrar', admin_category_path(category), method: :delete, data: { confirm: 'Estas seguro?' }, class:"btn btn-danger" %>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nueva categoria', new_admin_category_path, class:"btn btn-success" %>

backend/app/views/admin/categories/new.html.erb
<h1>Nueva Categoria</h1>

<%= render 'form', category: @category %>