backend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'image_groups/index'
    get 'image_groups/show'
    get 'configuracion_sitio', to: 'configuracion_sitio#index'
    resources :users
    resources :products
    resources :categories
    resources :tags
    resource :logos, only: [:edit, :update, :destroy, :show]
    resources :image_groups
    resources :products do
      member do
        delete 'remove_image/:image_id', to: 'products#remove_image', as: 'remove_image'
        delete 'remove_main_image/:main_image_id', to: 'products#remove_main_image', as: 'remove_main_image'
      end
    end
    resources :image_groups do
      member do
        get 'view', to: 'image_groups#view'
        post 'select', to: 'image_groups#select'
        patch :update, to: 'image_groups#update'
        delete :remove_image, to: 'image_groups#remove_image'
      end
      get 'favorite_image_group', on: :collection, to: 'image_groups#show_favorite', defaults: { format: :json }
    end
  end
  get 'tags', to: 'public_routes#show_tags', defaults: { format: :json }
  get 'categories', to: 'public_routes#show_categories', defaults: { format: :json }
  get 'logo', to: 'public_routes#show_logo', defaults: { format: :json }
  get 'favorite', to: 'public_routes#show_favorite', defaults: { format: :json }
  get 'products', to: 'public_routes#products', defaults: { format: :json }
  get 'products/:id', to: 'public_routes#show_product', defaults: { format: :json }
  get 'random_products', to: 'public_routes#random_products', defaults: { format: :json }
  get 'total_pages', to: 'public_routes#total_pages', defaults: { format: :json }
  get 'pages/home'
  root to: 'pages#home' 
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

end

backend/app/views/admin/shared/_image_groups.html.erb
<h1>Grupo de imagenes</h1>

<table class="table table-dark table-sm table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Favorito</th>
      <th>Imagen</th>
      <th>Acciones</th>
    </tr>
  </thead>
<div class="pagination">
<%= will_paginate @image_groups,  previous_label: '<', next_label: '>', page_links: false %>
</div>
  <tbody>
    <% @image_groups.each do |image_group| %>
      <tr>
        <td><%= image_group.name %></td>
        <td>
          <% if image_group.is_favorite? %>
            Si
          <% else %>
            No
          <% end %>
        </td>
           <td class="img-td", style='text-align: start;'>
          <% if image_group.images.present? %>
          <%= image_tag image_group.images.first, loading: 'lazy',style: 'max-width: 70px; max-height: 70px;' %>
          <% else %>
          <p>Este Grupo no tiene imágenes</p>
          <% end %>
        </td>
        <td>
         <div class="btn-group">
        <%= link_to 'Editar', edit_admin_image_group_path(image_group), class: "btn btn-primary" %>
        <%= link_to 'Borrar', admin_image_group_path(image_group), method: :delete, data: { confirm: '¿Estás seguro de que quieres borrar este grupo?' }, class: "btn btn-danger" %>
        <%= link_to 'Favorito', select_admin_image_group_path(image_group), method: :post, remote: true,  class: "btn btn-warning"%>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to "Nuevo grupo de imagenes", new_admin_image_group_path, class:"btn btn-success" %>

backend/app/views/admin/shared/_logo.html.erb
<h1>Logo</h1>

<div class="container-logo">
<% if @logo %>
  <div class="logo">
    <%= image_tag @logo.file if @logo.file.attached? %>
  </div>

 <div class="btn-group">
  <%= link_to "Editar Logo", edit_admin_logos_path(@logo), class:"btn btn-primary" %>
  <%= link_to "Eliminar Logo", admin_logos_path(@logo), method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn-danger" %>
</div>
<% else %>
<div>
  <p>No se ha cargado ningún logo todavía.</p>
  <%= link_to "Cargar logo", edit_admin_logos_path, class:"btn btn-success" %>
  <div>
<% end %>
<div>