backend/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'image_groups/index'
    get 'image_groups/show'
    get 'configuracion_sitio', to: 'configuracion_sitio#index'
    resources :users
    resources :products
    resources :categories
    resources :tags
    resource :logos, only: [:edit, :update, :destroy, :show]
    resources :image_groups
    resources :products do
      member do
        delete 'remove_image/:image_id', to: 'products#remove_image', as: 'remove_image'
        delete 'remove_main_image/:main_image_id', to: 'products#remove_main_image', as: 'remove_main_image'
      end
    end
    resources :image_groups do
      member do
        get 'view', to: 'image_groups#view'
        post 'select', to: 'image_groups#select'
        patch :update, to: 'image_groups#update'
        delete :remove_image, to: 'image_groups#remove_image'
      end
      get 'favorite_image_group', on: :collection, to: 'image_groups#show_favorite', defaults: { format: :json }
    end
  end
  get 'tags', to: 'public_routes#show_tags', defaults: { format: :json }
  get 'categories', to: 'public_routes#show_categories', defaults: { format: :json }
  get 'logo', to: 'public_routes#show_logo', defaults: { format: :json }
  get 'favorite', to: 'public_routes#show_favorite', defaults: { format: :json }
  get 'products', to: 'public_routes#products', defaults: { format: :json }
  get 'products/:id', to: 'public_routes#show_product', defaults: { format: :json }
  get 'random_products', to: 'public_routes#random_products', defaults: { format: :json }
  get 'total_pages', to: 'public_routes#total_pages', defaults: { format: :json }
  get 'pages/home'
  root to: 'pages#home' 
  devise_for :users, controllers: {
  registrations: 'users/registrations'
}

end

backend/app/views/layouts/_alerts.html.erb
<div id="flash-messages">
<p class="notice"><%= notice %></p>
<p class="alerta"><%= alert %></p>
</div>

backend/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-navbar position-button">
   <div class="container">
    <%= link_to 'Marca', root_path, class: "navbar-brand brand-space" %>

    <div>
      <ul class="navbar-nav ms-auto dropdown-space">
        <% if current_user %>
    <button id="toggleSidebar" class="sidebar-show-hide">&harr;</button>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.user_name %>
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li class="dropdown-item"><%= link_to 'Editar Cuenta', edit_admin_user_path(current_user) %></li>
            <li><hr class="dropdown-divider"></li>
            <li class="dropdown-item"><%= link_to 'Desconectarse', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li class="nav-item">
          <div>Debes iniciar sesion</div>
        </li>
        <% end %>
      </ul>
  </div>
    </div>

</nav>

backend/app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="sidebar-container">
    <ul class="sidebar-wrapper">
        <% if current_user %>
        <li>
          <%= link_to 'Productos', admin_products_path %>
        </li>
        <li>
          <%= link_to 'Categorias', admin_categories_path %>
        </li>
        <li>
          <%= link_to 'Tags', admin_tags_path %>
        </li>
        <li>
          <%= link_to 'Usuarios', admin_users_path %>
        </li>
        <li>
          <%= link_to "Configuración", admin_configuracion_sitio_path %>
        </li>
        <% else %>
        <li>
          <%= link_to 'Ingresar', new_user_session_path %>
        </li>
        <% end %>
      </ul>
</div>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/sidebar' %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>